### ISSUE TITLE
Error during Vagrant Up withouth "extras" defined on config.yml

### ISSUE THREAD

**Issue by davic-cit** [natanmoraes/simple-behat-vm#1]
As soon as i executed `Vagrant Up` for the first time i got this error: 
![picture_1](https://cloud.githubusercontent.com/assets/17763950/20360383/ad92a32c-ac1a-11e6-82a6-e64472c5866d.png)

And also, every other time i tried running the command after that i got the following errors:
![picture_2](https://cloud.githubusercontent.com/assets/17763950/20360384/ad92dc0c-ac1a-11e6-9020-a8c8e66b89e0.png)

While i got these errors, i did leave the config.yml withouth the "extras" as you can see:
![picture_3](https://cloud.githubusercontent.com/assets/17763950/20360385/ad949696-ac1a-11e6-8fca-2c8190fef28c.png)

And one more thing, if you leave the config.yml file with the "extras"  defined but withouth anything inside as you can see here:
![picture_4](https://cloud.githubusercontent.com/assets/17763950/20360382/ad922cc6-ac1a-11e6-99b3-bf8d89f88cf4.png)
You will end up with the following error when trying to execute `Vagrant Up`:
![picture_5](https://cloud.githubusercontent.com/assets/17763950/20360386/ad96e7ac-ac1a-11e6-908f-a0f609b3f1f7.png)

A possible explanation is that the setup is not expecting the "extras" as something that can be undefined.

**Comment by natanmoraes** [comment]
@davic-cit 
For the first issue, composer should be able to handle that problem. Check the log if symfony/config is being downloaded regardless of the error. Let me know if there is still a problem with that

For the other issues, they should be fixed now
